name = "portfolio-api"
main = "src/Api.ts" 
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "my-personal-portfolio"
database_id = "6663c46e-f2ab-4da4-9af0-ccd03afcb3e3"

[[routes]]
pattern = "personal-portfolio.syn-forge.com"
custom_domain = true